### PR TITLE
PR: Successfully added Contact Html and Universal.css

### PR DESCRIPTION
**Pull request by Hussain0531**
Contact.html  and Universal.Css are bug free and do not require any other requirements.

### CODE REVIEW

**Comment by Ahmad1122270** [comment]
issue 1 homepage

**Comment by Ahmad1122270** [comment]
done good to go

**Review by Ahmad1122270 — APPROVED** [review]
done good

**Review by Taseen679 — APPROVED** [review]
Done.

**Review by Ahmad1122270 — APPROVED** [review]
done

**Review by Allaulhaqbutt — APPROVED** [review]
yes good

**Pull request closed without merging**
